#Title
name: Java CI with Maven
#Events
on:
  pull_request:
    branches: [ "master","develop" ]
#Jobs
jobs:
  #Build Project
  Build:
    name: Build Project
    #If build failed on some OS
    continue-on-error: true
    #Various OS
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    #Sequence of Instructions
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  #Run Tests
  Test:
    name: Running tests
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      
      - uses: actions/checkout@v4
      - name: Run Test
        run: echo Test Completed
  #Package Project
  Package:
    name: Package Project
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Push artifacts
        run: |
          echo Push Artifacts
          
  
